# Generated by Django 4.2.6 on 2023-10-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['-ts']},
        ),
    ]
